#!/usr/bin/perl
use strict;
use warnings;
use Getopt::Long;
use Pod::Usage;
use JSON;
use CommitRater;


my %opts;
GetOptions \%opts, qw(
     remote|r=s
       help|h
) or pod2usage(2);

if (@ARGV)
{
    my $args = join ' ', @ARGV;
    warn "Excessive arguments: $args\n";
    pod2usage(2);
}

pod2usage(-exitval => 0, -verbose => 2) if $opts{help};

my $remote = $opts{remote} or pod2usage(1);


my $rater = CommitRater->new(repo => CommitRater::Repo->new(remote => $remote));
print JSON->new->utf8->pretty->canonical->encode($rater->rate);


__END__

=head1 NAME

commit-rater

=head1 SYNOPSIS

    commit-rater --remote=REMOTE

=cut
